// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQHV-Eh9fH54SrZKUT19eKdC46updbqQw',
    appId: '1:451151488028:web:fd383c2dc236df9e0f2bd9',
    messagingSenderId: '451151488028',
    projectId: 'ais-visaguard',
    authDomain: 'ais-visaguard.firebaseapp.com',
    storageBucket: 'ais-visaguard.firebasestorage.app',
    measurementId: 'G-KR9Y5MDQKC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkgjHiV8AJXc6Z1wPK0daXjM27XZA9M8A',
    appId: '1:451151488028:android:36316b7d8e8980220f2bd9',
    messagingSenderId: '451151488028',
    projectId: 'ais-visaguard',
    storageBucket: 'ais-visaguard.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADWgHwQ6O1zv6k3RiwMAlYcMsWmoN3JKs',
    appId: '1:451151488028:ios:d009db07746b3f9f0f2bd9',
    messagingSenderId: '451151488028',
    projectId: 'ais-visaguard',
    storageBucket: 'ais-visaguard.firebasestorage.app',
    iosBundleId: 'com.visaguard.app',
  );
}
